spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://localhost:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: my-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://localhost:8081




springdoc:
  swagger-ui:
    urls[1]:
      name: BON Service APIs
      url: /bon/v3/api-docs
    urls[2]:
      name: PRODUITS Service APIs
      url: /products/v3/api-docs
    urls[3]:
      url: /compte/v3/api-docs
      name: COMPTE Service APIs
    urls[0]:
      url: /auth/v3/api-docs
      name: AUTHENTIFICATION Service APIs
